### PR TITLE
Revert to older @itwin/eslint-plugin.

### PR DESCRIPTION
**Pull request by tcobbs-bentley**
The new one causes intermittent build errors. I don't know why they are intermittent, but when they happen, there is no way to get rid of them.

### CODE REVIEW

**Comment by toddsouthenbentley** [comment]
What are the intermittent build errors with the newer eslint plugin?

**Comment by toddsouthenbentley** [comment]
@aruniverse @MichaelBelousov  Any thoughts on this? I'd rather see us fix the underlying issue if we can.

**Comment by aruniverse** [comment]
not sure how this is happening. i agree id rather see the issue be fixed. 
travis, please look into fixing it if you can
there arent really any eslint experts on our team, we're all just inner sourcing contributions to it

**Comment by MichaelBelousov** [comment]
I saw the same issue deterministically reproducible in another internal application's repository... I suppose we could investigate there?

**Comment by tcobbs-bentley** [comment]
> not sure how this is happening. i agree id rather see the issue be fixed. travis, please look into fixing it if you can there arent really any eslint experts on our team, we're all just inner sourcing contributions to it

I tried for a number of hours and failed (including trying suggestions made by Michael). I think something is broken in @itwin/eslint-plugin, but I don't understand any of it enough to have any idea what it might be. I submitted an issue to the plugin.

**Comment by tcobbs-bentley** [comment]
> @aruniverse @MichaelBelousov Any thoughts on this? I'd rather see us fix the underlying issue if we can.

Given that right now I can't use iTwin Mobile samples **at all** without the contents of this PR, and I have to assume others will be in the same boat, I feel that this PR should be approved and merged. I definitely agree that fixing the underlying problem is important, but making it so people can run the samples is more important.

**Review by toddsouthenbentley — APPROVED** [review]

**Pull request merged**
