### PR TITLE
Switch to latest eslint-plugin pkg and switch to eslint flat config for react-app

### PR DESCRIPTION
**Pull request by anmolshres98**
Intended to solve https://github.com/iTwin/eslint-plugin/issues/48

### CODE REVIEW

**Comment by anmolshres98** [comment]
@tcobbs-bentley Please take a look and lmk what you think

**Comment by tcobbs-bentley** [comment]
As I originally [stated](https://github.com/iTwin/eslint-plugin/issues/48#issuecomment-1751013455) in the `@itwin/eslint-plugin` Issue that I created, I don't want to disable lint during build and start due to our repository not having any PR triggers to run lint. Furthermore, while you and I both can't make it happen right now with `npm run lint`, I know for a fact that it happened intermittently on @itwin/eslint-plugin/4.0.0-dev.48, and I suspect that it will continue to happen intermittently with dev.49.

**Comment by anmolshres98** [comment]
Is there a reason there no check builds that run during PRs on this repo? It seems that the code isn't built during PR's either, so based on what you said someone could still check in broken code that could not build since there are no checks at all?

**Comment by tcobbs-bentley** [comment]
With only two people making regular contributions to this repo, it was never felt that it was worth it.

**Comment by tcobbs-bentley** [comment]
As long as we continue to use @bentley/react-scripts, I think we will stick to the older @itwin/eslint-plugin, since the problem appears to be with @bentley/react-scripts.

**Pull request closed without merging**
